# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usbhid" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/e5c4d681-8d9b-4bab-a5fa-7282ce16c311";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  boot.initrd.luks.devices."cryptroot0".device = "/dev/disk/by-uuid/69099624-8a1e-41a5-a20d-5dc2e224c49a";

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/e5c4d681-8d9b-4bab-a5fa-7282ce16c311";
      fsType = "btrfs";
      options = [ "subvol=@var_log" ];
    };

  fileSystems."/.snapshots" =
    { device = "/dev/disk/by-uuid/e5c4d681-8d9b-4bab-a5fa-7282ce16c311";
      fsType = "btrfs";
      options = [ "subvol=@snapshots" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/e5c4d681-8d9b-4bab-a5fa-7282ce16c311";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/F479-E3F7";
      fsType = "vfat";
    };

  swapDevices = [ ];

  # high-resolution display
  hardware.video.hidpi.enable = lib.mkDefault true;
}
