# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/42e90c2a-42dd-4234-8f5d-fc8df7fbdb14";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  boot.initrd.luks.devices."cryptroot0".device = "/dev/disk/by-uuid/1968cdab-992e-481e-9c7a-16ee019016e3";

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/42e90c2a-42dd-4234-8f5d-fc8df7fbdb14";
      fsType = "btrfs";
      options = [ "subvol=@var_log" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/3D63-A5FC";
      fsType = "vfat";
    };

  fileSystems."/.snapshots" =
    { device = "/dev/disk/by-uuid/42e90c2a-42dd-4234-8f5d-fc8df7fbdb14";
      fsType = "btrfs";
      options = [ "subvol=@snapshots" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/42e90c2a-42dd-4234-8f5d-fc8df7fbdb14";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/mnt/stor" =
    { device = "/dev/disk/by-uuid/532605bb-8955-472c-8cb0-245448610829";
      fsType = "btrfs";
    };

  boot.initrd.luks.devices."cryptstore".device = "/dev/disk/by-uuid/e7c8ffc3-82cb-46e5-afd3-d72d28732a2e";

  swapDevices = [ ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "ondemand";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  # high-resolution display
  hardware.video.hidpi.enable = lib.mkDefault true;
}
